### ISSUE TITLE
QUESTION: Vue Composition API

### ISSUE THREAD

**Issue by JosefBredereck** [e-Spirit/fsxa-pwa#44]
Hello Devs,

Is there a planned schedule when the Vue composition API and a more recent version of Vue and Nuxt can be used?
Maybe there is already another repo that supports the Vue composition API. In that case, a hyperlink would be sufficient. 💯

**Comment by dbarczewski** [comment]
Hey @JosefBredereck, 

thanks for your question! 

Currently we are using the lastest version of Nuxt v2.15.8 in this project. 
Sadly Vue3 is not supported with Nuxt yet, so we cannot upgrade Vue itself. 

But since it is a basically Nuxt Project you *should* be able to use all nuxt modules you want to use. 
And there is a module that supports the Vue composition API: https://composition-api.nuxtjs.org/ 

Maybe give it a try. 

Let us know, if you have any other question!

**Comment by JosefBredereck** [comment]
Thanks for the fast replay; I will check the given information 🚀
